(function(){
  'use strict';
  const KEY='learnvault_focus_session_v2';
  const VIOL='learnvault_focus_violations_v2';
  const isStudentPage=/\/student\//.test(location.pathname);
  if(!isStudentPage) return;
  const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){return null}};
  const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
  const violations=()=>{try{return JSON.parse(localStorage.getItem(VIOL)||'[]')}catch(e){return[]}};
  const addViolation=(msg)=>{const a=violations();a.push({at:new Date().toISOString(),message:msg});localStorage.setItem(VIOL,JSON.stringify(a.slice(-100)));showToast('Focus warning: '+msg);};
  let session=get(), timer=null, toastTimer=null;
  function styles(){if(document.getElementById('lvFocusStyles'))return;const s=document.createElement('style');s.id='lvFocusStyles';s.textContent=`
#lvFocusSetup{position:fixed;inset:0;z-index:99990;background:rgba(7,10,24,.72);backdrop-filter:blur(3px);display:flex;align-items:center;justify-content:center;padding:20px}#lvFocusSetup.hidden{display:none}.lv-focus-card{width:min(520px,100%);background:#11182f;color:#fff;border:1px solid rgba(130,145,255,.35);border-radius:20px;padding:28px;box-shadow:0 24px 70px rgba(0,0,0,.45)}.lv-focus-card h2{margin:0 0 8px}.lv-focus-card p{color:#b9c2df;line-height:1.5}.lv-focus-duration{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}.lv-focus-duration button{border:1px solid #5965a8;background:#1a2343;color:#fff;border-radius:10px;padding:10px 14px;cursor:pointer}.lv-focus-duration button.active{background:#625cff;border-color:#817dff}.lv-focus-custom{display:flex;gap:8px;align-items:center;margin:10px 0 18px}.lv-focus-custom input{width:90px;padding:10px;border-radius:9px;border:1px solid #5965a8;background:#0c1227;color:#fff}.lv-focus-start{width:100%;padding:13px;border:0;border-radius:11px;background:#625cff;color:#fff;font-weight:800;cursor:pointer}.lv-focus-bar{position:fixed;top:0;left:0;right:0;z-index:99980;display:flex;align-items:center;justify-content:center;gap:14px;padding:8px 14px;background:#11182f;color:#fff;border-bottom:1px solid rgba(130,145,255,.35);font-size:13px}.lv-focus-bar strong{color:#aeb8ff}.lv-focus-end{border:0;border-radius:8px;padding:5px 9px;background:#2a345c;color:#fff;cursor:pointer}.lv-focus-toast{position:fixed;top:55px;right:18px;z-index:99999;background:#8b1e3f;color:#fff;padding:11px 15px;border-radius:10px;font-weight:700;display:none;box-shadow:0 8px 25px rgba(0,0,0,.35)}
`;document.head.appendChild(s)}
  function setup(){if(document.getElementById('lvFocusSetup'))return;const d=document.createElement('div');d.id='lvFocusSetup';d.innerHTML=`<div class="lv-focus-card"><h2>🎯 Start Focus Mode</h2><p>Choose how long you want to stay focused. You can continue using all LearnVault features during the session. Leaving LearnVault to another tab or website will be recorded as a focus violation.</p><div class="lv-focus-duration"><button data-min="15">15 min</button><button data-min="25" class="active">25 min</button><button data-min="45">45 min</button><button data-min="60">60 min</button></div><div class="lv-focus-custom"><span>Custom:</span><input id="lvFocusCustom" type="number" min="1" max="240" placeholder="minutes"><span>minutes</span></div><button class="lv-focus-start" id="lvFocusStart">Start Focus Mode</button></div>`;document.body.appendChild(d);let selected=25;d.querySelectorAll('[data-min]').forEach(b=>b.onclick=()=>{d.querySelectorAll('[data-min]').forEach(x=>x.classList.remove('active'));b.classList.add('active');selected=Number(b.dataset.min);d.querySelector('#lvFocusCustom').value=''});d.querySelector('#lvFocusStart').onclick=()=>{const custom=Number(d.querySelector('#lvFocusCustom').value);const mins=custom>0?Math.min(custom,240):selected;start(mins);d.remove()};}
  function bar(){let b=document.getElementById('lvFocusBar');if(!b){b=document.createElement('div');b.id='lvFocusBar';b.className='lv-focus-bar';b.innerHTML='<strong>🔒 Focus Mode</strong><span id="lvFocusClock"></span><span id="lvFocusViolationCount"></span><button class="lv-focus-end" id="lvFocusEnd">End Focus</button>';document.body.appendChild(b);b.querySelector('#lvFocusEnd').onclick=()=>finish(false)}updateBar()}
  function toast(msg){let t=document.getElementById('lvFocusToast');if(!t){t=document.createElement('div');t.id='lvFocusToast';t.className='lv-focus-toast';document.body.appendChild(t)}t.textContent=msg;t.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.style.display='none',3000)}
  function updateBar(){const b=document.getElementById('lvFocusBar');if(!b||!session)return;const left=Math.max(0,Math.ceil((session.endsAt-Date.now())/1000));const m=Math.floor(left/60),s=left%60;b.querySelector('#lvFocusClock').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')} remaining`;b.querySelector('#lvFocusViolationCount').textContent=`Violations: ${session.violationCount||0}`}
  function start(mins){session={startedAt:Date.now(),endsAt:Date.now()+mins*60000,durationMinutes:mins,violationCount:0};save(session);bar();if(timer)clearInterval(timer);timer=setInterval(()=>{if(!session)return;if(Date.now()>=session.endsAt){finish(true);return}updateBar()},1000)}
  function finish(auto){if(timer)clearInterval(timer);timer=null;localStorage.removeItem(KEY);const b=document.getElementById('lvFocusBar');if(b)b.remove();if(auto)toast('Focus session completed. Great work!');session=null}
  function active(){return !!session&&Date.now()<session.endsAt}
  function restore(){if(session&&!active()){finish(true);return}if(session){bar();timer=setInterval(()=>{if(Date.now()>=session.endsAt){finish(true)}else updateBar()},1000)}else if(session===null && new URLSearchParams(location.search).get('login')==='1'){setTimeout(setup,400)}}
  document.addEventListener('visibilitychange',()=>{if(active()&&document.hidden){session.violationCount=(session.violationCount||0)+1;save(session);updateBar();addViolation('You left LearnVault or switched to another tab');}});
  window.addEventListener('beforeunload',()=>{});
  styles();
  document.addEventListener('DOMContentLoaded',restore);
})();
