document.addEventListener('DOMContentLoaded', async () => {
  const role = document.body.dataset.role || document.body.dataset.commercialRole || '';
  const $ = id => document.getElementById(id);
  const esc = v => String(v ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const toast = msg => { const t=$('toast'); if(!t)return; t.textContent=msg; t.className='toast show'; clearTimeout(t._t); t._t=setTimeout(()=>t.className='toast',2600); };
  const form=$('liveClassForm'), list=$('liveClassList'), subject=$('liveClassSubject');
  async function me(){const r=await fetch('/api/auth/me',{credentials:'same-origin'});const j=await r.json();if(r.status===401){location.replace('../login.html');return null;}if(!r.ok||!j.user||String(j.user.role).toLowerCase()!==role)throw Error('Access denied');const n=$('liveClassHeaderName');if(n)n.textContent=j.user.fullName||role;return j.user;}
  async function loadSubjects(){if(role!=='faculty'||!subject)return;const r=await fetch('/api/faculty/subjects',{credentials:'same-origin'});if(!r.ok)return;const j=await r.json();const items=j.subjects||[];subject.innerHTML='<option value="">General class</option>'+items.map(s=>`<option value="${s.id}">${esc(s.subjectCode)} — ${esc(s.subjectName)}</option>`).join('');}
  function status(x){return String(x.status||'scheduled').replace('_',' ')}
  function render(items){if(!list)return;if(!items.length){list.innerHTML='<div class="integration-empty">No Live Classes available yet.</div>';return;}list.innerHTML=items.map(x=>`<article class="lv-feature-card"><div class="lv-feature-card-head"><div><span class="eyebrow">${esc(status(x).toUpperCase())}</span><h3>${esc(x.title)}</h3><p>${esc(x.subject_name||'General learning session')} ${x.course_name?'• '+esc(x.course_name):''} ${x.level_name?'• '+esc(x.level_name):''}</p></div><span class="lv-live-badge">${Number(x.participants||0)} joined</span></div><p>${esc(x.description||'Live teaching session on LearnVault.')}</p><div class="lv-feature-meta"><span>${new Date(x.starts_at).toLocaleString()}</span>${x.faculty_name?`<span>Faculty: ${esc(x.faculty_name)}</span>`:''}</div><div class="lv-feature-actions">${role==='student'?`<button class="button button-primary" data-join="${x.id}">${x.joined?'Rejoin':'Join Live Class'}</button>`:''}${role!=='student'?`<button class="button button-soft" data-status="${x.id}" data-next="${x.status==='live'?'completed':'live'}">${x.status==='live'?'End Class':'Start Class'}</button>`:''}${role==='admin'?'':`<button class="button button-ghost" data-open="${x.id}">Open Details</button>`}</div></article>`).join('');
    list.querySelectorAll('[data-join]').forEach(b=>b.onclick=async()=>{const r=await fetch(`/api/live-classes/${b.dataset.join}/join`,{method:'POST',credentials:'same-origin'});const j=await r.json();if(!r.ok)return toast(j.message||'Unable to join');window.open(j.meetingUrl,'_blank','noopener,noreferrer');await load();});
    list.querySelectorAll('[data-status]').forEach(b=>b.onclick=async()=>{const r=await fetch(`/api/live-classes/${b.dataset.status}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({status:b.dataset.next})});const j=await r.json();toast(j.message||'Updated');if(r.ok)load();});
  }
  async function load(){const r=await fetch('/api/live-classes',{credentials:'same-origin'});const j=await r.json();if(!r.ok)throw Error(j.message||'Unable to load Live Classes');render(j.classes||[]);}
  if(form){form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form);const body=Object.fromEntries(fd.entries());const r=await fetch('/api/live-classes',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(body)});const j=await r.json();toast(j.message||'Saved');if(r.ok){form.reset();load();}};}
  try{await me();await loadSubjects();await load();}catch(e){toast(e.message);}
});
