document.addEventListener("DOMContentLoaded", async () => {
    const toast=document.getElementById('toast'),loading=document.getElementById('studentQuizLoading'),content=document.getElementById('studentQuizContent'),quizList=document.getElementById('studentQuizList'),history=document.getElementById('studentQuizHistory'),top=document.getElementById('studentQuizTopSearch');let quizzes=[],attempts=[];
    const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
    const text=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v??'-';};
    function toastMsg(m){if(!toast)return;toast.textContent=m;toast.classList.add('show');clearTimeout(toast.hideTimer);toast.hideTimer=setTimeout(()=>toast.classList.remove('show'),2800);}
    async function requireStudent(){const r=await fetch('/api/auth/me',{credentials:'same-origin'}),j=await r.json();if(r.status===401){location.replace('../login.html');return null;}if(!r.ok||!j.user||String(j.user.role||'').toLowerCase()!=='student')throw new Error('Student access only');text('headerStudentName',j.user.fullName||'Student');return j.user;}
    async function loadQuizzes(){const r=await fetch('/api/quizzes/student',{credentials:'same-origin'}),j=await r.json();if(!r.ok)throw new Error(j.message||'Unable to load quizzes');quizzes=Array.isArray(j.quizzes)?j.quizzes:[];const p=j.profile||{};text('quizDomain',p.domainName||'General');text('quizCourse',p.courseName||'-');text('quizLevel',p.levelName||'Course-wide');text('studentAvailableQuizCount',quizzes.length);renderQuizzes();}
    function renderQuizzes(){const term=top.value.trim().toLowerCase(),rows=quizzes.filter(q=>!term||[q.title,q.subject_name,q.subject_code,q.unit_name].filter(Boolean).some(v=>String(v).toLowerCase().includes(term)));if(!rows.length){quizList.innerHTML='<div class="admin-empty-state large">No published quizzes match your course or search.</div>';return;}quizList.innerHTML=rows.map(q=>{const used=Number(q.attempts_used||0),max=Number(q.max_attempts||1),left=Math.max(0,max-used),best=q.best_percentage==null?null:Number(q.best_percentage);return `<article class="student-quiz-card"><div class="student-quiz-card-head"><div class="student-quiz-symbol">✓</div><div><span>${esc(q.subject_code)} — ${esc(q.subject_name)}</span><h3>${esc(q.title)}</h3></div></div><p>${esc(q.description||'Course quiz')}</p><div class="student-quiz-meta"><span>${q.question_count} Questions</span><span>${q.time_limit_minutes} min</span><span>Pass ${q.pass_percentage}%</span><span>${left} attempt${left===1?'':'s'} left</span></div>${q.unit_name?`<div class="student-quiz-unit">${esc(q.unit_name)}</div>`:''}<div class="student-quiz-card-bottom"><div>${best==null?'<span>No score yet</span>':`<span>Best score</span><strong>${best.toFixed(0)}%</strong>`}</div><button class="button button-primary" data-start="${q.id}" ${left<=0?'disabled':''}>${left<=0?'Attempts Used':'Start Quiz'}</button></div></article>`;}).join('');quizList.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',async()=>{try{b.disabled=true;b.textContent='Starting...';const r=await fetch(`/api/quizzes/student/${b.dataset.start}/start`,{method:'POST',credentials:'same-origin'}),j=await r.json();if(!r.ok)throw new Error(j.message||'Unable to start quiz');location.href=`quiz-attempt.html?attempt=${encodeURIComponent(j.attempt.id)}`;}catch(e){toastMsg(e.message);b.disabled=false;b.textContent='Start Quiz';}}));}
    async function loadHistory(){const r=await fetch('/api/quizzes/student/history',{credentials:'same-origin'}),j=await r.json();if(!r.ok)throw new Error(j.message||'Unable to load history');attempts=Array.isArray(j.attempts)?j.attempts:[];const done=attempts.filter(a=>a.status==='submitted');text('studentSubmittedAttemptCount',done.length);const best=done.length?Math.max(...done.map(a=>Number(a.percentage||0))):null;text('studentBestScore',best==null?'-':`${best.toFixed(0)}%`);if(!attempts.length){history.innerHTML='<div class="admin-empty-state large">You have not started a quiz yet.</div>';return;}history.innerHTML=attempts.map(a=>`<article class="quiz-history-row"><div><span>${esc(a.subject_code)} — ${esc(a.subject_name)}</span><strong>${esc(a.title)}</strong><small>Attempt #${a.attempt_number} • ${a.status==='submitted'?'Submitted':'In progress'}</small></div><div class="quiz-history-score">${a.status==='submitted'?`<strong>${Number(a.percentage).toFixed(0)}%</strong><span>${Number(a.percentage)>=Number(a.pass_percentage)?'Passed':'Needs improvement'}</span>`:'<strong>—</strong><span>Not submitted</span>'}</div><a class="button button-soft compact" href="${a.status==='submitted'?`quiz-result.html?attempt=${a.attempt_id}`:`quiz-attempt.html?attempt=${a.attempt_id}`}">${a.status==='submitted'?'View Result':'Continue'}</a></article>`).join('');}
    top.addEventListener('input',renderQuizzes);document.querySelectorAll('.rail-item[href="#"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();toastMsg('Peer Groups will be connected later.');}));document.getElementById('logoutButton').addEventListener('click',async()=>{try{await fetch('/api/auth/logout',{method:'POST',credentials:'same-origin'});}finally{location.replace('../login.html');}});
    try{if(!(await requireStudent()))return;await Promise.all([loadQuizzes(),loadHistory()]);loading.hidden=true;content.hidden=false;}catch(e){loading.innerHTML=`<strong>${esc(e.message)}</strong><span>Ask Admin to configure your course profile if needed.</span>`;toastMsg(e.message);}
});
