document.addEventListener('DOMContentLoaded', async () => {
  const $=id=>document.getElementById(id), params=new URLSearchParams(location.search), classId=params.get('id');
  const toast=msg=>{const t=$('toast');if(!t)return;t.textContent=msg;t.className='toast show';clearTimeout(t._t);t._t=setTimeout(()=>t.className='toast',2600)};
  let me=null, currentClass=null, peers=new Map(), joined=false, lastOfferIds=new Set();
  const rtcConfig={iceServers:[{urls:'stun:stun.l.google.com:19302'}]};
  async function auth(){const r=await fetch('/api/auth/me',{credentials:'same-origin'});const j=await r.json();if(r.status===401){location.replace('../login.html');return null;}if(!r.ok||!j.user||j.user.role!=='student')throw Error('Student access required');me=j.user;return me;}
  async function load(){const r=await fetch(`/api/live-classes/${classId}`,{credentials:'same-origin'});const j=await r.json();if(!r.ok)throw Error(j.message||'Class unavailable');currentClass=j.class;$('watchTitle').textContent=j.class.title;$('watchMeta').textContent=`${j.class.subject_name||'General'} • ${j.class.faculty_name||'Faculty'}`;$('watchParticipants').textContent=`${j.class.participants||0} watching`;$('watchStatus').textContent=String(j.class.status||'scheduled').toUpperCase();return j.class;}
  async function join(){const r=await fetch(`/api/live-classes/${classId}/join`,{method:'POST',credentials:'same-origin'});const j=await r.json();if(!r.ok)throw Error(j.message||'Unable to join');joined=true;return j;}
  async function answerOffer(o){if(lastOfferIds.has(o.id))return;lastOfferIds.add(o.id);const pc=new RTCPeerConnection(rtcConfig);peers.set(Number(o.from_user_id),pc);pc.ontrack=e=>{if(!$('liveVideo').srcObject)$('liveVideo').srcObject=e.streams[0];};await pc.setRemoteDescription(JSON.parse(o.payload));const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await waitIce(pc);await fetch(`/api/live-classes/${classId}/native/answer`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({payload:JSON.stringify(pc.localDescription)})});}
  async function waitIce(pc){if(pc.iceGatheringState==='complete')return;await new Promise(resolve=>{const fn=()=>{if(pc.iceGatheringState==='complete'){pc.removeEventListener('icegatheringstatechange',fn);resolve()}};pc.addEventListener('icegatheringstatechange',fn);setTimeout(resolve,8000);});}
  async function pollOffers(){const r=await fetch(`/api/live-classes/${classId}/native/offers`,{credentials:'same-origin'});if(!r.ok)return;const j=await r.json();for(const o of j.offers||[]){await answerOffer(o);}if(j.offers?.length&&$('livePlayerPlaceholder'))$('livePlayerPlaceholder').remove();}
  async function chat(){const r=await fetch(`/api/live-classes/${classId}/chat`,{credentials:'same-origin'});if(!r.ok)return;const j=await r.json();const box=$('chatMessages');if(!box)return;box.innerHTML=(j.messages||[]).map(m=>`<div class="live-chat-message"><strong>${String(m.full_name||'User').replace(/[<>&]/g,'')}</strong><span>${String(m.message||'').replace(/[<>&]/g,'')}</span></div>`).join('');box.scrollTop=box.scrollHeight;}
  async function sendChat(){const input=$('chatInput');if(!input?.value.trim())return;const r=await fetch(`/api/live-classes/${classId}/chat`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({message:input.value.trim()})});if(r.ok){input.value='';chat();}}
  async function questions(){const r=await fetch(`/api/live-classes/${classId}/questions`,{credentials:'same-origin'});if(!r.ok)return;const j=await r.json();const box=$('questionList');if(!box)return;box.innerHTML=(j.questions||[]).map(q=>`<div class="live-question"><strong>${String(q.full_name||'Student').replace(/[<>&]/g,'')}</strong><p>${String(q.question||'').replace(/[<>&]/g,'')}</p>${q.answer?`<div class="live-answer">Faculty: ${String(q.answer).replace(/[<>&]/g,'')}</div>`:''}</div>`).join('');}
  async function ask(){const i=$('questionInput');if(!i?.value.trim())return;const r=await fetch(`/api/live-classes/${classId}/questions`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({question:i.value.trim()})});if(r.ok){i.value='';questions();}}
  async function leave(){if(!joined)return;joined=false;for(const pc of peers.values())pc.close();peers.clear();navigator.sendBeacon(`/api/live-classes/${classId}/leave`,new Blob([JSON.stringify({})],{type:'application/json'}));}
  $('chatForm')?.addEventListener('submit',e=>{e.preventDefault();sendChat();});$('questionForm')?.addEventListener('submit',e=>{e.preventDefault();ask();});window.addEventListener('beforeunload',leave);
  try{if(!classId)throw Error('Missing Live Class id');await auth();const j=await join();await load();if(j.status!=='live')throw Error('This class is not live yet.');setInterval(()=>pollOffers().catch(()=>{}),1500);setInterval(()=>{chat().catch(()=>{});questions().catch(()=>{});load().catch(()=>{});},5000);await pollOffers();await chat();await questions();}catch(e){toast(e.message);}
});
